on: [push, pull_request]
name: "Check"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Luacheck"
    steps:
    - uses: actions/checkout@main
    - name: apt
      run: sudo apt-get install -y luarocks
    - name: install luacheck
      run: luarocks install --local luacheck
    - name: run luacheck
      run: $HOME/.luarocks/bin/luacheck ./

  mineunit:
    runs-on: ubuntu-latest
    name: "Mineunit tests"
    steps:
    - uses: actions/checkout@main
    - name: apt
      run: sudo apt-get install -y luarocks lua-bitop
    - name: install lua deps
      run: for x in busted luacov; do luarocks install --local $x; done
    - name: install mineunit
      # FIXME: this seems to be abandoned?
      run: luarocks install --server=https://luarocks.org/dev --local mineunit
    - name: run mesecons tests
      working-directory: ./mesecons/
      run: $HOME/.luarocks/bin/mineunit -q
    - name: run mesecons_mvps tests
      working-directory: ./mesecons_mvps/
      run: $HOME/.luarocks/bin/mineunit -q
    - name: run mesecons_fpga tests
      working-directory: ./mesecons_fpga/
      run: $HOME/.luarocks/bin/mineunit -q
    - name: run mesecons_luacontroller tests
      working-directory: ./mesecons_luacontroller/
      run: $HOME/.luarocks/bin/mineunit -q
